export enum GarmentColor {
  RED = 'red',
  PINK = 'pink',
  ORANGE = 'orange',
  YELLOW = 'yellow',
  GREEN = 'green',
  BLUE = 'blue',
  PURPLE = 'purple',
  BLACK = 'black',
  WHITE = 'white',
  GREY = 'grey',
  BEIGE = 'beige',
  BROWN = 'brown',
  GOLD = 'gold',
  SILVER = 'silver',
  PATTERN = 'pattern',
  OTHER = 'other',
}
